<?php
$title = 'Add new beer';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$beer = $form->get('name');
$beer->setAttribute('class', 'form-control');
$beer->setAttribute('placeholder', 'beer name');

// This provides a default CSS class and placeholder text for the artist element:
$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'description');

$cat_id = $form->get('cat_id');
$cat_id->setAttribute('class', 'form-control');
$cat_id->setAttribute('placeholder', 'category id');

$abv = $form->get('abv');
$abv->setAttribute('class', 'form-control');
$abv->setAttribute('placeholder', 'Alcohol by Volume');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('beer', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php 
	  // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within 
?>
<div class="form-group">
    <?= $this->formLabel($beer) ?>
    <?= $this->formElement($beer) ?>
    <?= $this->formElementErrors()->render($beer, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($cat_id) ?>
    <?= $this->formElement($cat_id) ?>
    <?= $this->formElementErrors()->render($cat_id, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($abv) ?>
    <?= $this->formElement($abv) ?>
    <?= $this->formElementErrors()->render($abv, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();