<?php
// module/beer/view/beer/beer/edit.phtml:

$title = 'Edit beer';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$beer = $form->get('name');
$beer->setAttribute('class', 'form-control');
$beer->setAttribute('placeholder', 'beer name');

$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');

$category = $form->get('cat_id');
$category->setAttribute('class', 'form-control');
$category->setAttribute('placeholder', 'category id');

$abv = $form->get('abv');
$abv->setAttribute('class', 'form-control');
$abv->setAttribute('placeholder', 'abv');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('beer', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($beer) ?>
    <?= $this->formElement($beer) ?>
    <?= $this->formElementErrors()->render($beer, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($category) ?>
    <?= $this->formElement($category) ?>
    <?= $this->formElementErrors()->render($category, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($abv) ?>
    <?= $this->formElement($abv) ?>
    <?= $this->formElementErrors()->render($abv, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();